In [1]:
# Data Acquisition and Exploration:
# Tasks: Identify and source the dataset(s), perform initial data exploration, and handle any missing or inconsistent data.

In [4]:
# Import the required libraries and dependencies
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

pd.plotting.register_matplotlib_converters()
%matplotlib inline
plt.style.use('seaborn-whitegrid')
pd.set_option('display.max_columns', 500)
warnings.filterwarnings("ignore")

In [ ]:
# Data Cleanup and Feature Engineering:
# Tasks: Clean and preprocess data, engineer new features, and prepare the dataset for model training.

In [ ]:
# Model Selection and Initial Training:
# Tasks: Select appropriate algorithms, train the initial models, and evaluate their performance.

In [ ]:
# Supervised learning model (e.g., Decision Tree, Random Forest, Logistic Regression)

In [ ]:
# Model Optimization and Finalization:
# Tasks: Optimize model parameters, test different feature combinations, and finalize the model.

In [ ]:
# API Integration and Data Visualization:
# Tasks: Implement API requests for additional data (if necessary), visualize key metrics, and create graphs to support the findings.

### Step 1:  Read in the `Bank_Personal_Loan_Modelling.csv` file and create a DataFrame.

In [6]:
# Read the CSV file into a Pandas DataFrame
# Set the index using the Ticker column
from google.colab import files

In [7]:
uploaded = files.upload()

Saving loan_approval_dataset.csv to loan_approval_dataset.csv

In [8]:
data_path = "loan_approval_dataset.csv"
df = pd.read_csv(
    data_path,
    parse_dates=True,
    index_col='loan_id'
)
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
loan_id,,,,,,,,,,,,
1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [9]:
print(df.head())

          no_of_dependents      education  self_employed   income_annum  \
loan_id
1                        2       Graduate             No        9600000
2                        0   Not Graduate            Yes        4100000
3                        3       Graduate             No        9100000
4                        3       Graduate             No        8200000
5                        5   Not Graduate            Yes        9800000

          loan_amount   loan_term   cibil_score   residential_assets_value  \
loan_id
1            29900000          12           778                    2400000
2            12200000           8           417                    2700000
3            29700000          20           506                    7100000
4            30700000           8           467                   18200000
5            24200000          20           382                   12400000

          commercial_assets_value   luxury_assets_value   bank_asset_value  \
loan_id
1                        17600000              22700000            8000000
2                         2200000               8800000            3300000
3                         4500000              33300000           12800000
4                         3300000              23300000            7900000
5                         8200000              29400000            5000000

         loan_status
loan_id
1           Approved
2           Rejected
3           Rejected
4           Rejected
5           Rejected

In [10]:
# Exploring the Data
df.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [11]:
# Check the columns and data types
print(df.info())

# Summary statistics of numerical columns
print(df.describe())
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4269 entries, 1 to 4269
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 433.6+ KB
None
        no_of_dependents   income_annum   loan_amount    loan_term  \
count        4269.000000   4.269000e+03  4.269000e+03  4269.000000
mean            2.498712   5.059124e+06  1.513345e+07    10.900445
std             1.695910   2.806840e+06  9.043363e+06     5.709187
min             0.000000   2.000000e+05  3.000000e+05     2.000000
25%             1.000000   2.700000e+06  7.700000e+06     6.000000
50%             3.000000   5.100000e+06  1.450000e+07    10.000000
75%             4.000000   7.500000e+06  2.150000e+07    16.000000
max             5.000000   9.900000e+06  3.950000e+07    20.000000

        cibil_score   residential_assets_value   commercial_assets_value  \
count   4269.000000               4.269000e+03              4.269000e+03
mean     599.936051               7.472617e+06              4.973155e+06
std      172.430401               6.503637e+06              4.388966e+06
min      300.000000              -1.000000e+05              0.000000e+00
25%      453.000000               2.200000e+06              1.300000e+06
50%      600.000000               5.600000e+06              3.700000e+06
75%      748.000000               1.130000e+07              7.600000e+06
max      900.000000               2.910000e+07              1.940000e+07

        luxury_assets_value   bank_asset_value
count          4.269000e+03       4.269000e+03
mean           1.512631e+07       4.976692e+06
std            9.103754e+06       3.250185e+06
min            3.000000e+05       0.000000e+00
25%            7.500000e+06       2.300000e+06
50%            1.460000e+07       4.600000e+06
75%            2.170000e+07       7.100000e+06
max            3.920000e+07       1.470000e+07
<class 'pandas.core.frame.DataFrame'>
Index: 4269 entries, 1 to 4269
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 433.6+ KB

In [12]:
# Check for missing values
print(df.isnull().sum())

 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [13]:
# Check for duplicates
print(df.duplicated().sum())

0

In [14]:
df[' loan_status'].value_counts()

 loan_status
 Approved    2656
 Rejected    1613
Name: count, dtype: int64

In [15]:
def status_change_int(loan_status):
    if (loan_status[' loan_status'] == ' Approved'):
        return 1
    return 0
df['loan_status']=df.apply(status_change_int,axis=1)
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,loan_status
loan_id,,,,,,,,,,,,,
1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,1
2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,0
3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,0
4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,0
5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,0

In [16]:
df["loan_status"].value_counts()

loan_status
1    2656
0    1613
Name: count, dtype: int64

In [17]:
y=df["loan_status"]
y

loan_id
1       1
2       0
3       0
4       0
5       0
       ..
4265    0
4266    1
4267    0
4268    1
4269    1
Name: loan_status, Length: 4269, dtype: int64

In [18]:
df[' education'].value_counts()

 education
 Graduate        2144
 Not Graduate    2125
Name: count, dtype: int64

In [20]:
df[' self_employed'].value_counts()

 self_employed
 Yes    2150
 No     2119
Name: count, dtype: int64

In [21]:
def employ_change_int(loan_status):
    if (loan_status[' self_employed'] ==' Yes'):
      return 1
    return 0
df[' self_employed'] = df.apply(employ_change_int, axis = 1)
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,loan_status
loan_id,,,,,,,,,,,,,
1,2,Graduate,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,1
2,0,Not Graduate,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,0
3,3,Graduate,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,0
4,3,Graduate,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,0
5,5,Not Graduate,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,0

In [22]:
def graduate_change_int(loan_status):
    if (loan_status[' education'] ==' Graduate'):
      return 1
    return 0
df[' education'] = df.apply(graduate_change_int, axis = 1)
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,loan_status
loan_id,,,,,,,,,,,,,
1,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,1
2,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,0
3,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,0
4,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,0
5,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,0

In [23]:
X = df.drop(columns=[" loan_status","loan_status"])

In [24]:
X

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
loan_id,,,,,,,,,,,
1,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
2,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
3,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
4,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
5,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4265,5,1,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4266,0,0,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4267,2,0,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4268,1,0,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4269,1,1,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=23)

In [26]:
logistic_regression_model = LogisticRegression(random_state=23)
logistic_regression_model.fit(X_train,y_train)

LogisticRegression(random_state=23)

In [27]:
print(f"Training Data Score: {logistic_regression_model.score(X_train,y_train)}")

Training Data Score: 0.7366447985004686

In [28]:
predictions = logistic_regression_model.predict(X_test)

In [29]:
# Create a confusion matrix
print(confusion_matrix(y_test,predictions,labels=[1,0]))

[[613  36]
 [261 158]]

In [30]:
from sklearn.metrics import confusion_matrix, classification_report, balanced_accuracy_score, roc_auc_score
print(classification_report(y_test,predictions, labels=[1,0]))

              precision    recall  f1-score   support

           1       0.70      0.94      0.80       649
           0       0.81      0.38      0.52       419

    accuracy                           0.72      1068
   macro avg       0.76      0.66      0.66      1068
weighted avg       0.75      0.72      0.69      1068

In [31]:
print(balanced_accuracy_score(y_test,predictions))

0.6608091758571109

In [33]:
print(balanced_accuracy_score(y_test,predictions))

0.6608091758571109

In [34]:
results_df = pd.DataFrame({"Prediction": predictions, "Actual": y_test})
results_df

         Prediction  Actual
loan_id
577               1       1
4240              0       0
3364              1       0
2436              0       0
3521              1       1
...             ...     ...
61                0       0
3558              1       0
750               1       1
1486              1       0
428               1       1

[1068 rows x 2 columns]

In [ ]:
credit_file = files.upload()

Saving credit_score.csv to credit_score.csv

In [ ]:
data_path1 = "credit_score.csv"
df1 = pd.read_csv(
    data_path1,
    parse_dates=True,
    index_col='CUST_ID'
)
df1

,INCOME,SAVINGS,DEBT,R_SAVINGS_INCOME,R_DEBT_INCOME,R_DEBT_SAVINGS,T_CLOTHING_12,T_CLOTHING_6,R_CLOTHING,R_CLOTHING_INCOME,R_CLOTHING_SAVINGS,R_CLOTHING_DEBT,T_EDUCATION_12,T_EDUCATION_6,R_EDUCATION,R_EDUCATION_INCOME,R_EDUCATION_SAVINGS,R_EDUCATION_DEBT,T_ENTERTAINMENT_12,T_ENTERTAINMENT_6,R_ENTERTAINMENT,R_ENTERTAINMENT_INCOME,R_ENTERTAINMENT_SAVINGS,R_ENTERTAINMENT_DEBT,T_FINES_12,T_FINES_6,R_FINES,R_FINES_INCOME,R_FINES_SAVINGS,R_FINES_DEBT,T_GAMBLING_12,T_GAMBLING_6,R_GAMBLING,R_GAMBLING_INCOME,R_GAMBLING_SAVINGS,R_GAMBLING_DEBT,T_GROCERIES_12,T_GROCERIES_6,R_GROCERIES,R_GROCERIES_INCOME,R_GROCERIES_SAVINGS,R_GROCERIES_DEBT,T_HEALTH_12,T_HEALTH_6,R_HEALTH,R_HEALTH_INCOME,R_HEALTH_SAVINGS,R_HEALTH_DEBT,T_HOUSING_12,T_HOUSING_6,R_HOUSING,R_HOUSING_INCOME,R_HOUSING_SAVINGS,R_HOUSING_DEBT,T_TAX_12,T_TAX_6,R_TAX,R_TAX_INCOME,R_TAX_SAVINGS,R_TAX_DEBT,T_TRAVEL_12,T_TRAVEL_6,R_TRAVEL,R_TRAVEL_INCOME,R_TRAVEL_SAVINGS,R_TRAVEL_DEBT,T_UTILITIES_12,T_UTILITIES_6,R_UTILITIES,R_UTILITIES_INCOME,R_UTILITIES_SAVINGS,R_UTILITIES_DEBT,T_EXPENDITURE_12,T_EXPENDITURE_6,R_EXPENDITURE,R_EXPENDITURE_INCOME,R_EXPENDITURE_SAVINGS,R_EXPENDITURE_DEBT,CAT_GAMBLING,CAT_DEBT,CAT_CREDIT_CARD,CAT_MORTGAGE,CAT_SAVINGS_ACCOUNT,CAT_DEPENDENTS,CREDIT_SCORE,DEFAULT
CUST_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
C02COQEVYU,33269,0,532304,0.0000,16.0000,1.2000,1889,945,0.5003,0.0568,0.0000,0.0035,0,0,0.5044,0.0000,0.1404,0.0000,3068,1554,0.5065,0.0922,0.0000,0.0058,0,0,1.3634,0.0000,0.0026,0.0000,1313,605,0.4608,0.0395,0.0000,0.0025,4849,2753,0.5677,0.1458,0.0000,0.0091,320,0,0.3314,0.0096,0.0055,0.0006,3006,1521,0.5060,0.0904,0.0000,0.0056,0,0,0.5322,0.0000,0.0276,0.0000,17893,11439,0.6393,0.5378,0.0000,0.0336,931,469,0.5038,0.0280,0.0655,0.0017,33269,19286,0.5797,1.0000,0.0000,0.0625,High,1,0,0,0,0,444,1
C02OZKC0ZF,77158,91187,315648,1.1818,4.0909,3.4615,5818,111,0.0191,0.0754,0.0638,0.0184,0,0,0.5001,0.0000,0.0000,0.0000,17244,8694,0.5042,0.2235,0.1891,0.0546,0,0,1.0542,0.0000,0.0000,0.0000,0,0,0.5431,0.0000,0.0000,0.0000,5224,2386,0.4567,0.0677,0.0573,0.0166,467,110,0.2355,0.0061,0.0051,0.0015,16339,8269,0.5061,0.2118,0.1792,0.0518,1973,988,0.5008,0.0256,0.0216,0.0063,20234,3133,0.1548,0.2622,0.2219,0.0641,2845,1423,0.5002,0.0369,0.0312,0.0090,70144,25114,0.3580,0.9091,0.7692,0.2222,No,1,0,0,1,0,625,0
C03FHP2D0A,30917,21642,534864,0.7000,17.3000,24.7142,1157,860,0.7433,0.0374,0.0535,0.0022,0,0,0.5022,0.0000,0.0000,0.0000,3611,2231,0.6178,0.1168,0.1669,0.0068,36,36,1.0000,0.0012,0.0017,0.0001,1201,609,0.5071,0.0388,0.0555,0.0022,4335,2418,0.5578,0.1402,0.2003,0.0081,891,387,0.4343,0.0288,0.0412,0.0017,2759,1395,0.5056,0.0892,0.1275,0.0052,0,0,0.5166,0.0000,0.0000,0.0000,16072,9251,0.5756,0.5198,0.7426,0.0300,855,431,0.5041,0.0277,0.0395,0.0016,30917,17618,0.5698,1.0000,1.4286,0.0578,High,1,0,0,1,0,469,1
C03PVPPHOY,80657,64526,629125,0.8000,7.8000,9.7499,6857,3686,0.5376,0.0850,0.1063,0.0109,4402,2215,0.5032,0.0546,0.0682,0.0070,13446,6849,0.5094,0.1667,0.2084,0.0214,0,0,0.0000,0.0000,0.0000,0.0000,7796,4056,0.5203,0.0967,0.1208,0.0124,4547,2355,0.5179,0.0564,0.0705,0.0072,2068,795,0.3844,0.0256,0.0320,0.0033,12619,6387,0.5061,0.1565,0.1956,0.0201,1675,915,0.5463,0.0208,0.0260,0.0027,25038,11835,0.4727,0.3104,0.3880,0.0398,2209,1112,0.5034,0.0274,0.0342,0.0035,80657,40205,0.4985,1.0000,1.2500,0.1282,High,1,0,0,1,0,559,0
C04J69MUX0,149971,1172498,2399531,7.8182,16.0000,2.0465,1978,322,0.1628,0.0132,0.0017,0.0008,0,0,0.5029,0.0000,0.0000,0.0000,5194,2675,0.5150,0.0346,0.0044,0.0022,0,0,0.5872,0.0000,0.0000,0.0000,1734,912,0.5260,0.0116,0.0015,0.0007,34814,15369,0.4415,0.2321,0.0297,0.0145,7513,2581,0.3435,0.0501,0.0064,0.0031,42658,21589,0.5061,0.2844,0.0364,0.0178,3941,1794,0.4552,0.0263,0.0034,0.0016,28167,12334,0.4379,0.1878,0.0240,0.0117,10338,5190,0.5020,0.0689,0.0088,0.0043,136337,62766,0.4604,0.9091,0.1163,0.0568,High,1,1,1,1,1,473,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CZQHJC9HDH,328892,1465066,5501471,4.4546,16.7273,3.7551,16701,10132,0.6067,0.0508,0.0114,0.0030,0,0,0.5060,0.0000,0.0000,0.0000,9778,4926,0.5038,0.0297,0.0067,0.0018,0,0,0.3163,0.0000,0.0000,0.0000,3216,1446,0.4496,0.0098,0.0022,0.0006,74781,38607,0.5163,0.2274,0.0510,0.0136,14270,7337,0.5142,0.0434,0.0097,0.0026,79932,40453,0.5061,0.2430,0.0546,0.0145,6712,3360,0.5006,0.0204,0.0046,0.0012,74298,39295,0.5289,0.2259,0.0507,0.0135,19305,9702,0.5026,0.0587,0.0132,0.0035,298993,155258,0.5193,0.9091,0.2041,0.0543,High,1,1,1,1,1,418,0
CZRA4MLB0P,81404,88805,680837,1.0909,8.3637,7.6667,5400,1936,0.3585,0.0663,0.0608,0.0079,0,0,0.5013,0.0000,0.0000,0.0000,28839,18396,0.6379,0.3543,0.3247,0.0424,0,0,0.5737,0.0000,0.0000,0.0000,0,0,0.4641,0.0000,0.0000,0.0000,7033,3590,0.5105,0.0864,0.0792,0.0103,1737,502,0.2890,0.0213,0.0196,0.0026,0,0,0.5060,0.0000,0.0000,0.0000,2890,1446,0.5003,0.0355,0.0325,0.0042,24625,3859,0.1567,0.3025,0.2773,0.0362,3480,1741,0.5003,0.0427,0.0392,0.0051,74004,31470,0.4252,0.9091,0.8333,0.1087,No,1,0,0,1,0,589,1
CZSOD1KVFX,0,42428,30760,3.2379,8.1889,0.7250,0,0,0.8779,0.0047,0.0000,0.0000,0,0,0.5026,0.0000,0.0000,0.0000,0,0,0.6163,0.3664,0.0000,0.0000,0,0,0.6442,0.0005,0.0000,0.0000,0,0,0.5861,0.0190,0.0000,0.0000,608,345,0.5674,0.1656,0.0143,0.0198,147,113,0.7687,0.0000,0.0035,0.0048,780,394,0.5051,0.2051,0.0184,0.0254,0,0,0.4953,0.0346,0.0000,0.0000,8804,6891,0.7827,0.1382,0.2075,0.2862,268,135,0.5037,0.0741,0.0063,0.0087,10607,7878,0.7427,1.0668,0.2500,0.3448,No,1,0,0,1,0,499,0
CZWC76UAUT,36011,8002,604181,0.2222,16.7777,75.5037,1993,1271,0.6377,0.0553,0.2491,0.0033,9622,4819,0.5008,0.2672,1.2024,0.0159,3587,1831,0.5105,0.0996,0.4483,0.0059,0,0,0.8037,0.0000,0.0000,0.0000,0,0,0.5768,0.0000,0.0000,0.0000,6049,3576,0.5912,0.1680,0.7559,0.0100,871,348,0.3995,0.0242,0.1088,0.0014,3549,1796,0.5061,0.0986,0.4435,0.0059,0,0,0.4917,0.0000,0.0000,0.0000,13244,11824,0.8928,0.3678,1.6551,0.0219,1097,550,0.5014,0.0305,0.1371,0.0018,40012,26015,0.6502,1.1111,5.0002,0.0662,No,1,1,0,1,0,507,0
CZZV5B3SAL,44266,309859,44266,6.9999,1.0000,0.1429,1574,1264,0.8030,0.0356,0.0051,0.0356,0,0,0.5019,0.0000,0.0000,0.0000,7496,3805,0.5076,0.1693,0.0242,0.1693,0,0,1.1978,0.0000,0.0000,0.0000,0,0,0.4962,0.0000,0.0000,0.0000,8371,3973,0.4746,0.1891,0.0270,0.1891,9093,3911,0.4301,0.2054,0.0293,0.2054,0,0,0.5061,0.0000,0.0000,0.0000,374,170,0.4545,0.0084,0.0012,0.0084,18840,8471,0.4496,0.4256,0.0608,0.4256,3436,1719,0.5003,0.0776,0.0111,0.0776,49184,23313,0.4740,1.1111,0.1587,1.1111,No,1,0,0,1,0,657,0

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, C02COQEVYU to CZZV5B3SAL
Data columns (total 86 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   INCOME                   1000 non-null   int64
 1   SAVINGS                  1000 non-null   int64
 2   DEBT                     1000 non-null   int64
 3   R_SAVINGS_INCOME         1000 non-null   float64
 4   R_DEBT_INCOME            1000 non-null   float64
 5   R_DEBT_SAVINGS           1000 non-null   float64
 6   T_CLOTHING_12            1000 non-null   int64
 7   T_CLOTHING_6             1000 non-null   int64
 8   R_CLOTHING               1000 non-null   float64
 9   R_CLOTHING_INCOME        1000 non-null   float64
 10  R_CLOTHING_SAVINGS       1000 non-null   float64
 11  R_CLOTHING_DEBT          1000 non-null   float64
 12  T_EDUCATION_12           1000 non-null   int64
 13  T_EDUCATION_6            1000 non-null   int64
 14  R_EDUCATION              1000 non-null   float64
 15  R_EDUCATION_INCOME       1000 non-null   float64
 16  R_EDUCATION_SAVINGS      1000 non-null   float64
 17  R_EDUCATION_DEBT         1000 non-null   float64
 18  T_ENTERTAINMENT_12       1000 non-null   int64
 19  T_ENTERTAINMENT_6        1000 non-null   int64
 20  R_ENTERTAINMENT          1000 non-null   float64
 21  R_ENTERTAINMENT_INCOME   1000 non-null   float64
 22  R_ENTERTAINMENT_SAVINGS  1000 non-null   float64
 23  R_ENTERTAINMENT_DEBT     1000 non-null   float64
 24  T_FINES_12               1000 non-null   int64
 25  T_FINES_6                1000 non-null   int64
 26  R_FINES                  1000 non-null   float64
 27  R_FINES_INCOME           1000 non-null   float64
 28  R_FINES_SAVINGS          1000 non-null   float64
 29  R_FINES_DEBT             1000 non-null   float64
 30  T_GAMBLING_12            1000 non-null   int64
 31  T_GAMBLING_6             1000 non-null   int64
 32  R_GAMBLING               1000 non-null   float64
 33  R_GAMBLING_INCOME        1000 non-null   float64
 34  R_GAMBLING_SAVINGS       1000 non-null   float64
 35  R_GAMBLING_DEBT          1000 non-null   float64
 36  T_GROCERIES_12           1000 non-null   int64
 37  T_GROCERIES_6            1000 non-null   int64
 38  R_GROCERIES              1000 non-null   float64
 39  R_GROCERIES_INCOME       1000 non-null   float64
 40  R_GROCERIES_SAVINGS      1000 non-null   float64
 41  R_GROCERIES_DEBT         1000 non-null   float64
 42  T_HEALTH_12              1000 non-null   int64
 43  T_HEALTH_6               1000 non-null   int64
 44  R_HEALTH                 1000 non-null   float64
 45  R_HEALTH_INCOME          1000 non-null   float64
 46  R_HEALTH_SAVINGS         1000 non-null   float64
 47  R_HEALTH_DEBT            1000 non-null   float64
 48  T_HOUSING_12             1000 non-null   int64
 49  T_HOUSING_6              1000 non-null   int64
 50  R_HOUSING                1000 non-null   float64
 51  R_HOUSING_INCOME         1000 non-null   float64
 52  R_HOUSING_SAVINGS        1000 non-null   float64
 53  R_HOUSING_DEBT           1000 non-null   float64
 54  T_TAX_12                 1000 non-null   int64
 55  T_TAX_6                  1000 non-null   int64
 56  R_TAX                    1000 non-null   float64
 57  R_TAX_INCOME             1000 non-null   float64
 58  R_TAX_SAVINGS            1000 non-null   float64
 59  R_TAX_DEBT               1000 non-null   float64
 60  T_TRAVEL_12              1000 non-null   int64
 61  T_TRAVEL_6               1000 non-null   int64
 62  R_TRAVEL                 1000 non-null   float64
 63  R_TRAVEL_INCOME          1000 non-null   float64
 64  R_TRAVEL_SAVINGS         1000 non-null   float64
 65  R_TRAVEL_DEBT            1000 non-null   float64
 66  T_UTILITIES_12           1000 non-null   int64
 67  T_UTILITIES_6            1000 non-null   int64
 68  R_UTILITIES              1000 non-null   float64
 69  R_UTILITIES_INCOME       1000 non-null   float64
 70  R_UTILITIES_SAVINGS      1000 non-null   float64
 71  R_UTILITIES_DEBT         1000 non-null   float64
 72  T_EXPENDITURE_12         1000 non-null   int64
 73  T_EXPENDITURE_6          1000 non-null   int64
 74  R_EXPENDITURE            1000 non-null   float64
 75  R_EXPENDITURE_INCOME     1000 non-null   float64
 76  R_EXPENDITURE_SAVINGS    1000 non-null   float64
 77  R_EXPENDITURE_DEBT       1000 non-null   float64
 78  CAT_GAMBLING             1000 non-null   object
 79  CAT_DEBT                 1000 non-null   int64
 80  CAT_CREDIT_CARD          1000 non-null   int64
 81  CAT_MORTGAGE             1000 non-null   int64
 82  CAT_SAVINGS_ACCOUNT      1000 non-null   int64
 83  CAT_DEPENDENTS           1000 non-null   int64
 84  CREDIT_SCORE             1000 non-null   int64
 85  DEFAULT                  1000 non-null   int64
dtypes: float64(51), int64(34), object(1)
memory usage: 712.0+ KB

In [ ]:
credit_file_approval = files.upload()

Saving application_record.csv to application_record.csv

In [ ]:
data_path2 = "application_record.csv"
df2 = pd.read_csv(
    data_path2,
    parse_dates=True,
    index_col='ID'
)
df2

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
ID,,,,,,,,,,,,,,,,,
5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6840104,M,N,Y,0,135000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-22717,365243,1,0,0,0,NaN,1.0
6840222,F,N,N,0,103500.0,Working,Secondary / secondary special,Single / not married,House / apartment,-15939,-3007,1,0,0,0,Laborers,1.0
6841878,F,N,N,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169,-372,1,1,0,0,Sales staff,1.0
6842765,F,N,Y,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673,365243,1,0,0,0,NaN,2.0
6842885,F,N,Y,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858,-1201,1,0,1,0,Sales staff,2.0

In [ ]:
loan_file_approval = files.upload()

Saving loan_approval_dataset (1).csv to loan_approval_dataset (1).csv

In [ ]:
data_path3 = "loan_approval_dataset (1).csv"
df3 = pd.read_csv(
    data_path3,
    parse_dates=True,
    index_col='loan_id'
)
df3

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
loan_id,,,,,,,,,,,,
1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

### Step 2: Scale the `` DataFrame and create a new DataFrame that contains the scaled data.

### Step 5: Create a scatter plot to visualize the "" using  "" as the x-variable and "MeanPercentReturn" as the y-variable.

### Step 6: Reduce the number of features to two principal components on the `df_stocks_scaled` DataFrame, and  calculate the explained variance ratio that results from the PCA data.

### Step 7: Use the calculate PCA DataFrame in Step 6 to create a new DataFrame called, ``, then add an additional column to the `` DataFrame that contains the tickers from the original `` DataFrame.

### Step 8: Rerun the K-means algorithm on the `` DataFrame and create a scatter plot using the  "" and the two principal components for the x- and y-axes. Be sure to style and format your plot.

**Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

**Answer:** We can conclude that using less features we can more clearly identify three clusters.

### Step 9. Determine which features have the strongest influence on each componen, and plot the most influencial features for each component.

### Which features have the strongest influence on each component?
---
**Answer:**
- "MeanOpen", "MeanHigh", "MeanLow", and "MeanClose" have the strongest positive influence on PCA1.
- "MeanVolume" has the strongest positive influence on PCA2.

### Step 10: Create a scatterplot of the most influential features for each principal component and stock cluster.

### Step 11: What is the difference between the segmentation results of the PCA DataFrame and most influential features for each component?

**Answer:** It appears that the most influential features for each component are; "MeanHigh" and "MeanVolume", however, plotting these features does not yield similar results as plotting each principal component. Suggesting that more than one feature is influencing one or principal components.